
2020-12-25 19:53:13,473 ERROR
File: [Cursor.py]
Line: [16]
Message: "Error al regresar el cursor 'psycopg2.extensions.cursor' object is not callable"

2020-12-25 19:53:13,473 ERROR
File: [Cursor.py]
Line: [22]
Message: "Ha ocurrido un error al guardar los datos en la Base de datos <class 'AttributeError'>"

2020-12-25 19:53:56,450 ERROR
File: [Cursor.py]
Line: [16]
Message: "Error al regresar el cursor 'psycopg2.extensions.cursor' object is not callable"

2020-12-25 19:53:56,450 ERROR
File: [Cursor.py]
Line: [22]
Message: "Ha ocurrido un error al guardar los datos en la Base de datos <class 'AttributeError'>"

2020-12-25 20:26:39,075 ERROR
File: [Cursor.py]
Line: [22]
Message: "Ha ocurrido un error al guardar los datos en la Base de datos <class 'psycopg2.errors.SyntaxError'>"

2020-12-25 20:26:39,075 ERROR
File: [UsuarioCrud.py]
Line: [54]
Message: "No se pudo actualizar el usuario Id: 9
Nombre: Update
Password: Update
 error: syntax error at or near "UDPATE"
LINE 1: UDPATE usuarios SET nombre = 'Update', password = 'Update' W...
        ^
"

